# Generated by Django 4.1.4 on 2022-12-16 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
